### ISSUE TITLE
Win whl troubles

### ISSUE THREAD

**Issue by tin2tin** [ubisoft/videotracks#1]
Unfortunately doesn't the whl work for me on Windows. Running Blender as admin didn't work and manually installing it this way produced this error:
`python -m pip install "C:\Users\45239\Downloads\VideoTracks_V0-1-31_alpha1\videotracks\otio\OpenTimelineIO-0.12.1-cp37-cp37m-win_amd64.whl"
ERROR: OpenTimelineIO-0.12.1-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.`

I know this is relying on the OTIO folks to finally share a working wheel for windows, which they hopefully will do soon.

Using a OTIO build by LazyDodo in a folder makes it run in 3.0 Alpha, but the channel headers do not show up. Is there anything else I need to do other than clicking the "Overlay toggle"?

**Comment by werwack** [comment]
Hi @tin2tin 
Thanks for sharing your issue.
The trouble you mention about the whl is on which version of Blender?
I haven't tried VideoTracks on V3.0 A yet but I will and let you know asap for the headers not showing up.

**Comment by werwack** [comment]
Fix will be in the version of VT supporting Blender 3.x

**Comment by werwack** [comment]
Fixed on v 0.2.1
