### ISSUE TITLE
Module Not Found Error: No module named 'opentimelineio'

### ISSUE THREAD

**Issue by carlosmu** [ubisoft/videotracks#2]
When I try to install the addon this happens (also in admin mode, in Blender 2.83 LTS).

`Module Not Found Error: No module named 'opentimelineio'`

![imagen](https://user-images.githubusercontent.com/21176686/131207363-9b41bd85-4189-4d4e-bc97-2752def48dc8.png)

**Comment by tin2tin** [comment]
There is no otio module for Blender 2.93(python 3.9) yet, so try with an earlier version of Blender.

**Comment by werwack** [comment]
Indeed. I will work on a version of the add-on that can run without the import of OpenTimelineIO, it will help while the wheel is being created somewhere in the community (that's a bit out of reach for me...)

**Comment by werwack** [comment]
Video Tracks will be reworked to support Blender 3.x. The integration of OpentTimelineIO will be part of it.
ETA: Mid December

**Comment by werwack** [comment]
Fixed on v 0.2.1
